spring:
  mail:
    host: mailhog
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.ssl.enable: false
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:api_sentinel}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2s

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

sentinel:
  target:
    defaultEnv: docker
  notify:
    resendIntervalSec: 600
    ackResendEnabled: false
    default-to: "dev@local.test"
    from: "api-sentinel@local.test"
    channelEnabled:
      email: true
    tag-routes:
      payment: pay@fluffycat.com
      order: order@fluffycat.com
    env-routes:
      docker: on-call@fluffycat.com
      local: dev@fluffycat.com
  probe:
    env: docker
    batch-size: 20
    lease-sec: 30
    tick-ms: 1000
