spring:
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.ssl.enable: false
  datasource:
    url: jdbc:mysql://127.0.0.1:${DB_PORT:3307}/${DB_NAME:api_sentinel}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

sentinel:
  target:
    defaultEnv: local
  notify:
    resendIntervalSec: 60
    ackResendEnabled: false
    default-to: "dev@local.test"
    from: "api-sentinel@local.test"
    channelEnabled:
      email: true
    tag-routes:
      payment: pay@fluffycat.com, pay-dev@fluffycat.com
      order: order@fluffycat.com
    env-routes:
      docker: on-call@fluffycat.com
      local: dev@fluffycat.com


#logging:
#  level:
#    com.zaxxer.hikari: DEBUG
#    org.springframework.jdbc: DEBUG
